# https://wiki.alpinelinux.org/wiki/MariaDB

FROM alpine:3.15

EXPOSE 3306

WORKDIR /

RUN apk update && \
    apk add --no-cache openrc mariadb mariadb-client

RUN openrc && touch /run/openrc/softlevel

COPY ./init.sh /

RUN chmod +x init.sh

CMD ["./init_db.sh"]
