version: "2.5"

services:
  nginx:
    depends_on:
      - wordpress
    build:
      context: .
      dockerfile: Dockerfile_nginx
    image: mynginx
    ports:
      - 80:80 # should be 443:443
    volumes:
      - wordpress:/wordpress

  wordpress:
    depends_on:
      - mariadb
    build:
        context: .
        dockerfile: Dockerfile_wordpress

  mariadb:
    build:
      context: .
      dockerfile: Dockerfile_mariadb
    image: mymariadb
    volumes:
      - db:/var/lib/mysql

# use for named volumes
volumes:
  wordpress:
  db:


# HOW TO RUN IT
# docker compose up -d
# docker compose logs -f [service]
# docker compose down [--volumes]

# NOTE
# wait for the mariadb to start before launching wordpress, use smth like 'wait-port'