FROM alpine:3.15

EXPOSE 9000

WORKDIR /

COPY ./init_wp.sh /

RUN apk update && \
    apk add --no-cache openrc php7-fpm

RUN openrc && \
    touch /run/openrc/softlevel && \
    wget http://wordpress.org/latest.tar.gz && \
    tar -xzf latest.tar.gz && \
    rm -f latest.tar.gz && \
    chmod +x init_wp.sh

CMD ["./init_wp.sh"]

# wget http://wordpress.org/latest.tar.gz
# tar -xzf latest.tar.gz
# rm -f latest.tar.gz
# MAYBE chown -R user:group /wordpress
# sed -i "s/define( 'DB_NAME', 'database_name_here' );/define( 'DB_NAME', '' );/g" /wordpress/wp-config-sample.php
# sed -i "s/define( 'DB_USER', 'username_here' );/define( 'DB_USER', '' );/g" /wordpress/wp-config-sample.php
# sed -i "s/define( 'DB_PASSWORD', 'password_here' );/define( 'DB_PASSWORD', '' );/g" /wordpress/wp-config-sample.php
# sed -i "s/define( 'DB_HOST', 'localhost' );/define( 'DB_HOST', '' );/g" /wordpress/wp-config-sample.php
# mv /wordpress/wp-config-sample.php /wordpress/wp-config.php

# using WP-CLI
# apk add lighttpd php7-common php7-session php7-iconv php7-json php7-gd php7-curl php7-xml php7-mysqli php7-imap php7-cgi fcgi php7-pdo php7-pdo_mysql php7-soap php7-xmlrpc php7-posix php7-mcrypt php7-gettext php7-ldap php7-ctype php7-dom php7-simplexml
# wget https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
# chmod +x wp-cli.phar
# mv wp-cli.phar /usr/bin/wp-cli
# wp-cli core download
# wp-cli config create --dbname=YOUR_DB_NAME --dbuser=YOUR_DB_USERNAME --dbpass=YOUR_DB_PASSWORD --locale=en_DB
# wp-cli core install --url=YOUR_DOMAIN_NAME --title=YOUR_BLOG_TITLE --admin_user=ADMIN_USERNAME --admin_password=ADMIN_PASSWORD --admin_email=ADMIN_EMAIL
