FROM alpine:3.15

EXPOSE 3306

WORKDIR /

RUN apk update && \
    apk add \
        mariadb \
        mariadb-client \
        openrc \
    && \
    rm -rf /var/cache/apk/*

RUN openrc && touch /run/openrc/softlevel

# https://wiki.alpinelinux.org/wiki/MariaDB
RUN /etc/init.d/mariadb setup && \
    /etc/init.d/mariadb start

CMD ["mysql", "-u", "root"]
